### ISSUE TITLE
Game Crashes[BUG]

### ISSUE THREAD

**Issue by KarlKnopf** [Panquesito7/minetest-instant_sapling_growth#4]
### Description of the bug

Whenever I plant a sapling the game crashes. Here is the log.
AsyncErr: Lua: Runtime error from mod '' in callback item_OnPlace(): ...-5.8.0-win64\bin\..\mods\instant_sapling_growth\init.lua:235: attempt to call upvalue 'old_after_place_node' (a nil value)
stack traceback:
	...-5.8.0-win64\bin\..\mods\instant_sapling_growth\init.lua:235: in function 'after_place_node'
	...-win64\bin\..\games\minetest_game\mods\default/trees.lua:510: in function 'sapling_on_place'
	...-win64\bin\..\games\minetest_game\mods\default/nodes.lua:1011: in function <...-win64\bin\..\games\minetest_game\mods\default/nodes.lua:1010>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Panquesito7** [comment]
Hey there! The issue should be fixed on the latest commit. Could you please give it a try? Thanks. 🙂

**Comment by KarlKnopf** [comment]
Yes! now trees seem to not grow when I plant them, I even tried toggling growth settings.

**Comment by KarlKnopf** [comment]
Thank you!
