### ISSUE TITLE
[BUG] Saplings Won't grow.

### ISSUE THREAD

**Issue by KarlKnopf** [Panquesito7/minetest-instant_sapling_growth#5]
### Description of the bug

The saplings don't grow when I plant them.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Panquesito7** [comment]
Hey there! Are you sure you have the `sapling_growth` privilege?

**Comment by KarlKnopf** [comment]
I did't know that existed, thank you!
